apiVersion: v1
kind: ConfigMap
metadata:
  name: tracker-config
  namespace: tracker
  labels:
    app: tracker
    component: microservice
data:
  SPRING_PROFILES_ACTIVE: "prod"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/tracker"

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  SERVER_SERVLET_CONTEXT_PATH: "/api/v1"

  AUTH_WHITELIST: "/swagger-ui.html,/v3/api-docs/**,/swagger-ui/**,/actuator,/actuator/**"
  AUTH_ALLOWED_ORIGINS: "http://192.168.49.2:30173"

  SCHEDULING_MESSAGING_CRON: "0 0 0 * * *"


