apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
  namespace: tracker
  labels:
    app: tracker
    component: microservice
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tracker
      component: microservice
  template:
    metadata:
      labels:
        app: tracker
        component: microservice
        version: v1
    spec:
      containers:
        - name: tracker
          image: task-tracker-tracker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: tracker-config
            - secretRef:
                name: tracker-secret
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"

