apiVersion: v1
kind: Service
metadata:
  name: tracker
  namespace: tracker
  labels:
    app: tracker
    component: microservice
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
      nodePort: 30080
  selector:
    app: tracker
    component: microservice


