apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: tracker
  labels:
    app: auth
    component: microservice
data:
  SPRING_PROFILES_ACTIVE: "prod"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/tracker"

  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  KAFKA_TOPICS_EMAIL_NAME: "email-topic"
  KAFKA_TOPICS_SMS_NAME: "sms-topic"
  KAFKA_TOPICS_PUSH_NAME: "push-topic"

  SERVER_SERVLET_CONTEXT_PATH: "/api/v1/auth"
  SERVER_PORT: "8081"

  AUTH_WHITELIST: "/signup,/login,/refresh,/logout,/swagger-ui.html,/v3/api-docs/**,/swagger-ui/**,/actuator,/actuator/**"
  AUTH_ALLOWED_ORIGINS: "http://192.168.49.2:30173"


