apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: tracker
  labels:
    app: auth
    component: microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: auth
    component: microservice


