apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: tracker
  labels:
    app: kafka
    component: broker
spec:
  clusterIP: None
  ports:
    - name: controller
      port: 9093
      targetPort: 9093
      protocol: TCP
    - name: listener
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
    component: broker


