apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: tracker
  labels:
    app: notification
    component: microservice
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification
      component: microservice
  template:
    metadata:
      labels:
        app: notification
        component: microservice
        version: v1
    spec:
      containers:
        - name: notification
          image: task-tracker-notification:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8040
              protocol: TCP
          envFrom:
            - configMapRef:
                name: notification-config
            - secretRef:
                name: auth-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"