apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: tracker
  labels:
    app: notification
    component: microservice
type: Opaque
stringData:
  SPRING_MAIL_USERNAME: "email@example.com"
  SPRING_MAIL_PASSWORD: "password"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"