apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: tracker
  labels:
    app: notification
    component: microservice
spec:
  type: NodePort
  ports:
    - name: http
      port: 8040
      targetPort: 8040
      protocol: TCP
      nodePort: 30040
  selector:
    app: notification
    component: microservice


