apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: tracker
  labels:
    app: frontend
    component: microservice
data:
  VITE_APP_TRACKER_URL: http://192.168.49.2:30080/api/v1
  VITE_APP_AUTH_URL: http://192.168.49.2:30081/api/v1/auth