apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: tracker
  labels:
    app: frontend
    component: microservice
data:
  VITE_APP_TRACKER_URL: http://localhost:8080/api/v1
  VITE_APP_AUTH_URL: http://localhost:8081/api/v1/auth