apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tracker
  labels:
    app: frontend
    component: microservice
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      component: microservice
  template:
    metadata:
      labels:
        app: frontend
        component: microservice
        version: v1
    spec:
      containers:
        - name: frontend
          image: task-tracker-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: frontend
              containerPort: 5173
              protocol: TCP
          envFrom:
            - configMapRef:
                name: frontend-config
          livenessProbe:
            httpGet:
              path: /health
              port: frontend
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: frontend
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"

