apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tracker
  labels:
    app: frontend
    component: microservice
spec:
  type: NodePort
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      protocol: TCP
      nodePort: 30173
  selector:
    app: frontend
    component: microservice


