spring:
  application:
    name: notification
  kafka:
    consumer:
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}-submission
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.shimady.tracker.model.messaging"
            type:
              mapping: com.shimady.tracker.model.messaging.EmailMessage:com.shimady.notification.model.EmailMessage,
                com.shimady.tracker.model.messaging.PushMessage:com.shimady.notification.model.PushMessage,
                com.shimady.tracker.model.messaging.ReminderMessage:com.shimady.notification.model.ReminderMessage,
                com.shimady.tracker.model.messaging.SMSMessage:com.shimady.notification.model.SMSMessage
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

kafka:
  topics:
    email:
      name: emailTopic
      replication-factor: 1
      partitions: 1
    sms:
      name: smsTopic
      replication-factor: 1
      partitions: 1
    push:
      name: pushTopic
      replication-factor: 1
      partitions: 1
    reminder:
      name: reminderTopic
      replication-factor: 1
      partitions: 1

logging:
  level:
    root: info