spring:
  application:
    name: tracker
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  kafka:
    producer:
      client-id: ${spring.application.name}
      enable-idempotence: true
      acks: all
      linger-ms: 100
      retry-backoff-ms: 1000
      delivery-timeout-ms: 30000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

auth:
  whitelist: /swagger-ui.html, /v3/api-docs/**, /swagger-ui/**, /actuator, /actuator/**
  allowed-origins: http://localhost:5173

server:
  servlet:
    context-path: /api/v1

kafka:
  topics:
    reminder:
      name: reminderTopic
      replication-factor: 1
      partitions: 1

logging:
  level:
    root: info

scheduling:
  messaging:
    cron: 0 0 0 * * *

