apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: tracker
  labels:
    app: postgres
    component: database
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: tracker


