name: Test
on: 
  push:
    paths:
    - 'tracker/**'
  pull_request:
    paths: 
    - 'tracker/**'
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Run tests with gradle
      working-directory: './tracker'
      run: ./gradlew test
